# Generated by Django 5.2 on 2025-04-12 23:35

# blog/migrations/XXXX_fill_missing_slugs.py
from django.db import migrations
from django.utils.text import slugify

def fill_slugs(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    for post in Post.objects.filter(slug__isnull=True) | Post.objects.filter(slug__exact=''):
        post.slug = slugify(post.title)
        original_slug = post.slug
        counter = 1
        while Post.objects.filter(slug=post.slug).exclude(id=post.id).exists():
            post.slug = f"{original_slug}-{counter}"
            counter += 1
        post.save()

class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0004_alter_post_slug'),  # Remplacez par votre dernière migration
    ]

    operations = [
        migrations.RunPython(fill_slugs),
    ]