# Generated by Django 5.2 on 2025-04-12 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='marques/')),
            ],
        ),
        migrations.CreateModel(
            name='Montre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('genre', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('U', 'Unisexe')], max_length=1)),
                ('disponible', models.BooleanField(default=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.collection')),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.marque')),
            ],
        ),
        migrations.CreateModel(
            name='ImageMontre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='montres/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('montre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.montre')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
