# Generated by Django 5.2 on 2025-04-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_collection_marque_montre_imagemontre'),
    ]

    operations = [
        migrations.AddField(
            model_name='montre',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
