# Generated by Django 5.2 on 2025-04-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_montre_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='montre',
            name='mouvement',
            field=models.CharField(choices=[('AUTO', 'Automatique'), ('QUARTZ', 'Quartz'), ('MECA', 'Mécanique'), ('SMART', 'Smartwatch')], default='QUARTZ', max_length=10, verbose_name='Type de mouvement'),
        ),
    ]
