# Generated by Django 5.2 on 2025-04-12 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_panier_itempanier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='date_modification',
        ),
        migrations.CreateModel(
            name='PanierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('montre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.montre')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.panier')),
            ],
        ),
        migrations.DeleteModel(
            name='ItemPanier',
        ),
    ]
