# Generated by Django 5.2 on 2025-04-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_panier_date_modification_panieritem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemontre',
            name='image',
            field=models.ImageField(upload_to='images/montres/'),
        ),
    ]
