# Generated by Django 5.2 on 2025-04-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_imagemontre_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemontre',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
