# Generated by Django 5.2 on 2025-04-12 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_imagemontre_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemontre',
            options={},
        ),
    ]
