# Generated by Django 5.2 on 2025-04-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_imagemontre_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemontre',
            name='image',
            field=models.ImageField(upload_to='montres/'),
        ),
    ]
