# Generated by Django 5.2 on 2025-04-12 21:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_codepromo_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieAccessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='categories_accessoires/')),
            ],
        ),
        migrations.CreateModel(
            name='Accessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('marque', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(upload_to='accessoires/')),
                ('en_stock', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessoires', to='shop.categorieaccessoire')),
            ],
        ),
    ]
