# Generated by Django 5.2 on 2025-04-13 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_commande_adresse_facturation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LignePanierAccessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('accessoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.accessoire')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_accessoires', to='shop.panier')),
            ],
            options={
                'unique_together': {('panier', 'accessoire')},
            },
        ),
    ]
