# Generated by Django 5.2 on 2025-04-13 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_lignepanieraccessoire'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lignepanieraccessoire',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='panier',
            name='lignes_accessoires',
            field=models.ManyToManyField(through='shop.LignePanierAccessoire', to='shop.accessoire'),
        ),
        migrations.AlterField(
            model_name='lignepanieraccessoire',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_accessoires_items', to='shop.panier'),
        ),
    ]
