# Generated by Django 5.2 on 2025-04-13 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_lignepanieraccessoire_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='lignes_accessoires',
        ),
        migrations.AlterField(
            model_name='lignepanieraccessoire',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_accessoires', to='shop.panier'),
        ),
        migrations.AlterField(
            model_name='panieritem',
            name='montre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panier_items', to='shop.montre'),
        ),
        migrations.AlterField(
            model_name='panieritem',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panier_items', to='shop.panier'),
        ),
    ]
